config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index" 
  resources :posts do
    resources :comments
  end
  resource :images, only: [:new, :create]
  resource :links, only: [:new, :create]
  resource :articles, only: [:new, :create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :comments, as: :commentable
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :comments, as: :commentable
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, as: :commentable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  
  end
  
  def create
    @article = Post.new(article_params)
    if @article.save
      redirect_to '/'
    else
      render action: "new"
    end
  end
  
  private
  
  def article_params
    params.require(:article).permit(:content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
  
  end
  
  def create
    @image = Image.new(image_params)
    
    if @image.save
      redirect_to '/'
    else
      render action: "new"
    end
  end
  
  private
  
  def image_params
    params.require(:image).permit(:url)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def new
  
  end
  
  def create
    @link = Link.new(link_params)
    
    if @link.save
      redirect_to '/'
    else
      render action: "new"
    end
  end
  
  private
  
  def link_params
    params.require(:link).permit(:url)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @images = Image.all
    @links = Link.all
    @articles = Post.all
    @posts = (@images + @links + @articles).sort_by {|x| x.created_at}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/new.html.erb
<h2>
Posts:
</h2>
<br \>
<%= form_for :article, url: articles_path do |f| %>
	<p>
		<%= f.label :content %><br/>
		<%= f.text_area :content %>
	</p>	
	<p>
		<%= f.submit 'Save', id: "Blabla" %><br/>

	</p>
<% end %>

app/views/images/new.html.erb
<h2>
Pictures:
</h2>
<br \>
<%= form_for :image, url: images_path do |f| %>
	<p>
		<%= f.label :url %><br/>
		<%= f.text_field :url %>
	</p>	
	<p>
		<%= f.submit 'Save', id: "Blabla" %><br/>

	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PolyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/new.html.erb
<h2>
Links:
</h2>
<br \>
<%= form_for :link, url: links_path do |f| %>
	<p>
		<%= f.label :url %><br/>
		<%= f.text_field :url %>
	</p>	
	<p>
		<%= f.submit 'Save', id: "Blabla" %><br/>

	</p>
<% end %>

app/views/posts/index.html.erb
<h1>
	Статьи:
</h1>
<% @posts.each do |post| %>
	<%= post.inspect %>
	<tr \>
	<br \>
<% end %>